make_handoff_readme <- function(...) {
  defaults <- list(
    handoff_type = resolve_handoff_type("marimo-notebook", "python"),
    source_filename = "handoff.py",
    summary = "A notebook that charts survival by class.",
    install_instructions = "```bash\npip install marimo pandas altair\n```",
    run_instructions = "Run it with:\n```bash\nmarimo edit handoff.py\n```",
    data_instructions = "A CSV named titanic.csv is bundled alongside.",
    bundled_files = "titanic.csv"
  )
  args <- utils::modifyList(defaults, list(...))
  do.call(build_handoff_readme, args)
}

describe("build_handoff_readme()", {
  it("includes the title and summary", {
    out <- make_handoff_readme()

    expect_match(out, "# Marimo Handoff", fixed = TRUE)
    expect_match(
      out,
      "A notebook that charts survival by class.",
      fixed = TRUE
    )
  })

  it("uses the current run instructions", {
    out <- make_handoff_readme(
      run_instructions = "Run it with:\n```bash\nRscript handoff.R\n```"
    )

    expect_match(out, "## Running this handoff", fixed = TRUE)
    expect_match(out, "Rscript handoff.R", fixed = TRUE)
  })

  it("lists the source and bundled files", {
    out <- make_handoff_readme()

    expect_match(out, "`handoff.py`", fixed = TRUE)
    expect_match(out, "`titanic.csv`", fixed = TRUE)
  })

  it("includes install and data sections", {
    out <- make_handoff_readme()

    expect_match(out, "## Installing dependencies", fixed = TRUE)
    expect_match(out, "pip install marimo pandas altair", fixed = TRUE)
    expect_match(out, "## Data", fixed = TRUE)
  })

  it("includes the AI disclaimer", {
    expect_match(make_handoff_readme(), "generated by AI", fixed = TRUE)
  })

  it("omits the run section when there are no run instructions", {
    other_type <- HandoffType(
      id = "other",
      label = "Mystery",
      icon = "file-earmark-code",
      language = "python",
      file_extension = ".txt",
      editor_language = "plain",
      structure = "text"
    )
    out <- make_handoff_readme(
      handoff_type = other_type,
      source_filename = "handoff.txt",
      run_instructions = ""
    )

    expect_no_match(out, "## Running this handoff", fixed = TRUE)
  })

  it("omits bundled file lines when there are none", {
    out <- make_handoff_readme(bundled_files = character())

    expect_no_match(out, "`titanic.csv`", fixed = TRUE)
    expect_match(out, "`handoff.py`", fixed = TRUE)
  })

  it("describes an external-data warning without claiming a bundled file", {
    out <- make_handoff_readme(
      data_instructions = handoff_external_dataframe_instructions(
        "tips",
        "DuckDB",
        "python"
      ),
      bundled_files = character()
    )

    expect_match(
      out,
      "This setup may need adjustment before the handoff can run.",
      fixed = TRUE
    )
    expect_match(
      out,
      "This handoff requires user-supplied data access.",
      fixed = TRUE
    )
    expect_match(
      out,
      paste(
        "File paths, connection details, or credentials may need",
        "configuration before running."
      ),
      fixed = TRUE
    )
    expect_no_match(out, "`tips.csv`", fixed = TRUE)
  })

  it("omits the summary section when empty", {
    out <- make_handoff_readme(summary = "")

    expect_match(out, "# Marimo Handoff\n\n## Files", fixed = TRUE)
  })

  it("omits the install section when empty", {
    out <- make_handoff_readme(install_instructions = "")

    expect_no_match(out, "## Installing dependencies", fixed = TRUE)
  })
})

describe("build_handoff_zip()", {
  it("contains the source, README, and bundled files", {
    zip_bytes <- build_handoff_zip(
      source = "print('hi')",
      source_filename = "handoff.py",
      readme = "# Readme",
      bundled_files = list(`titanic.csv` = charToRaw("a,b\n1,2\n"))
    )
    zip_path <- withr::local_tempfile(fileext = ".zip")
    writeBin(zip_bytes, zip_path)

    expect_setequal(
      zip::zip_list(zip_path)$filename,
      c("handoff.py", "README.md", "titanic.csv")
    )
  })

  it("omits bundled files when there are none", {
    zip_bytes <- build_handoff_zip(
      source = "x",
      source_filename = "handoff.qmd",
      readme = "# R",
      bundled_files = list()
    )
    zip_path <- withr::local_tempfile(fileext = ".zip")
    writeBin(zip_bytes, zip_path)

    expect_setequal(
      zip::zip_list(zip_path)$filename,
      c("handoff.qmd", "README.md")
    )
  })
})
