from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._artifact_types import ArtifactType

DISCLAIMER = (
    "> ⚠️ This artifact was generated by AI from a querychat session. Review the "
    "code, dependencies, and run instructions before executing it, and verify any "
    "results against your data."
)


def build_readme(
    *,
    artifact_type: ArtifactType,
    source_filename: str,
    summary: str,
    install_instructions: str,
    run_instructions: str,
    data_instructions: str,
    bundled_files: list[str],
) -> str:
    sections: list[str] = [f"# {artifact_type.label} Artifact"]

    if summary:
        sections.append(summary)

    file_lines = [f"- `{source_filename}` — the {artifact_type.label} source"] + [
        f"- `{name}` — bundled data file"
        for name in bundled_files
        if name != source_filename
    ]
    sections.append("## Files\n" + "\n".join(file_lines))

    if install_instructions:
        sections.append("## Installing dependencies\n" + install_instructions)

    if run_instructions:
        sections.append("## Running this artifact\n" + run_instructions)

    if data_instructions:
        if bundled_files:
            data_header = (
                "Each bundled CSV file is a fixed CSV snapshot captured when this "
                "artifact was generated."
            )
        else:
            data_header = (
                "This artifact requires live data access and credentials before "
                "running."
            )
        sections.append("## Data\n" + data_header + "\n\n" + data_instructions)

    sections.append("---\n" + DISCLAIMER)

    return "\n\n".join(sections) + "\n"
