build_handoff_readme <- function(
  handoff_type,
  source_filename,
  summary,
  install_instructions,
  run_instructions,
  data_instructions,
  bundled_files
) {
  sections <- paste0("# ", handoff_type@label, " Handoff")

  if (nzchar(summary)) {
    sections <- c(sections, summary)
  }

  data_files <- setdiff(bundled_files, source_filename)
  file_lines <- c(
    paste0(
      "- `",
      source_filename,
      "` \u2014 the ",
      handoff_type@label,
      " source"
    ),
    paste0("- `", data_files, "` \u2014 bundled data file")
  )
  sections <- c(
    sections,
    paste0("## Files\n", paste(file_lines, collapse = "\n"))
  )

  if (nzchar(install_instructions)) {
    sections <- c(
      sections,
      paste0("## Installing dependencies\n", install_instructions)
    )
  }

  if (nzchar(run_instructions)) {
    sections <- c(
      sections,
      paste0("## Running this handoff\n", run_instructions)
    )
  }

  if (nzchar(data_instructions)) {
    data_header <- if (length(bundled_files) > 0L) {
      paste(
        "Each bundled CSV file is a fixed CSV snapshot captured when this",
        "handoff was generated."
      )
    } else {
      paste(
        "This handoff requires user-supplied data access. File paths,",
        "connection details, or credentials may need configuration before",
        "running."
      )
    }
    sections <- c(
      sections,
      paste0("## Data\n", data_header, "\n\n", data_instructions)
    )
  }

  sections <- c(
    sections,
    paste0(
      "---\n> \u26a0\ufe0f This handoff was generated by AI from a querychat ",
      "session. Review the code, dependencies, and run instructions before ",
      "executing it, and verify any results against your data."
    )
  )

  paste0(paste(sections, collapse = "\n\n"), "\n")
}

build_handoff_zip <- function(source, source_filename, readme, bundled_files) {
  dir <- tempfile("querychat-handoff-")
  dir.create(dir)
  on.exit(unlink(dir, recursive = TRUE, force = TRUE), add = TRUE)

  writeBin(charToRaw(enc2utf8(source)), file.path(dir, source_filename))
  writeBin(charToRaw(enc2utf8(readme)), file.path(dir, "README.md"))
  for (name in names(bundled_files)) {
    writeBin(bundled_files[[name]], file.path(dir, name))
  }

  archive <- tempfile("querychat-handoff-", fileext = ".zip")
  on.exit(unlink(archive, force = TRUE), add = TRUE)
  zip::zipr(
    archive,
    files = c(source_filename, "README.md", names(bundled_files)),
    root = dir
  )

  readBin(archive, "raw", file.info(archive)$size)
}
