"""
Shared regex patterns for querychat playwright tests.

These patterns match common SQL WHERE clauses and chat response content
generated by the LLM when querying the Titanic dataset.
"""

import re

# ==================== SQL WHERE clause patterns ====================

# Filter by sex
SQL_FEMALE_FILTER = re.compile(r"WHERE.*sex.*=.*['\"]?female['\"]?", re.IGNORECASE)
SQL_MALE_FILTER = re.compile(r"WHERE.*sex.*=.*['\"]?male['\"]?", re.IGNORECASE)

# Filter by survived
SQL_SURVIVED_FILTER = re.compile(r"WHERE.*survived.*=.*(1|TRUE)", re.IGNORECASE)

# Filter by class
SQL_FIRST_CLASS_FILTER = re.compile(
    r"WHERE.*(p?class).*=.*(1|['\"]First['\"])", re.IGNORECASE
)

# ==================== Chat response patterns ====================

# Survival-related responses - must mention survival context with a number
RESPONSE_SURVIVAL = re.compile(r"(surviv\w*.*\d+|\d+.*surviv\w*)", re.IGNORECASE)

# Age-related responses - must mention age context with a number
RESPONSE_AGE = re.compile(r"(age.*\d+\.?\d*|\d+\.?\d*.*age|average.*\d+)", re.IGNORECASE)

# Fare-related responses - must mention fare context with a number
RESPONSE_FARE = re.compile(r"(fare.*\d+\.?\d*|\d+\.?\d*.*fare|average.*\d+)", re.IGNORECASE)

# Class-related responses - must mention class context
RESPONSE_CLASS = re.compile(
    r"(class.*\d+|\d+.*(first|second|third)|count.*class)", re.IGNORECASE
)
RESPONSE_FIRST_CLASS = re.compile(r"first.class|class.1|first.class.passenger", re.IGNORECASE)
RESPONSE_FILTER = re.compile(r"filter|showing|display|first.class", re.IGNORECASE)
RESPONSE_MALE_FILTER = re.compile(r"male.passenger|filter.*male|showing.*male", re.IGNORECASE)

# ==================== Greeting/suggestion patterns ====================

GREETING_SUGGESTIONS = re.compile(r"survived|class|age", re.IGNORECASE)
GREETING_SUGGESTIONS_FULL = re.compile(
    r"survived|class|age|passenger", re.IGNORECASE
)
GREETING_SUGGESTIONS_FILTER = re.compile(
    r"survived|class|age|passenger|filter", re.IGNORECASE
)
