"""
Shared regex patterns for querychat playwright tests.

These patterns match common SQL WHERE clauses and chat response content
generated by the LLM when querying the Titanic dataset.
"""

import re

# ==================== SQL WHERE clause patterns ====================

# Filter by sex
SQL_FEMALE_FILTER = re.compile(r"WHERE.*sex.*=.*['\"]?female['\"]?", re.IGNORECASE)
SQL_MALE_FILTER = re.compile(r"WHERE.*sex.*=.*['\"]?male['\"]?", re.IGNORECASE)

# Filter by survived
SQL_SURVIVED_FILTER = re.compile(r"WHERE.*survived.*=.*1|TRUE", re.IGNORECASE)

# Filter by class
SQL_FIRST_CLASS_FILTER = re.compile(
    r"WHERE.*(p?class).*=.*(1|['\"]First['\"])", re.IGNORECASE
)

# ==================== Chat response patterns ====================

# Survival-related responses
RESPONSE_SURVIVAL = re.compile(r"survived|survival|\d+", re.IGNORECASE)

# Age-related responses (including average)
RESPONSE_AGE = re.compile(r"average|age|\d+\.?\d*", re.IGNORECASE)

# Fare-related responses (including average)
RESPONSE_FARE = re.compile(r"average|fare|\d+\.?\d*", re.IGNORECASE)

# Class-related responses
RESPONSE_CLASS = re.compile(r"class|count|first|second|third|\d+", re.IGNORECASE)
RESPONSE_FIRST_CLASS = re.compile(r"(first|class|passenger)", re.IGNORECASE)
RESPONSE_FILTER = re.compile(r"first|class|filter", re.IGNORECASE)
RESPONSE_MALE_FILTER = re.compile(r"male|filter|showing", re.IGNORECASE)

# ==================== Greeting/suggestion patterns ====================

GREETING_SUGGESTIONS = re.compile(r"survived|class|age", re.IGNORECASE)
GREETING_SUGGESTIONS_FULL = re.compile(
    r"survived|class|age|passenger", re.IGNORECASE
)
GREETING_SUGGESTIONS_FILTER = re.compile(
    r"survived|class|age|passenger|filter", re.IGNORECASE
)
