from querychat._artifact_readme import build_readme
from querychat._artifact_types import ARTIFACT_TYPES, ArtifactType


def make_readme(**overrides):
    kwargs = {
        "artifact_type": ARTIFACT_TYPES["marimo-notebook"],
        "source_filename": "artifact.py",
        "summary": "A notebook that charts survival by class.",
        "install_instructions": "```bash\npip install marimo pandas altair\n```",
        "data_instructions": "A CSV named titanic.csv is bundled alongside.",
        "bundled_files": ["titanic.csv"],
    }
    kwargs.update(overrides)
    return build_readme(**kwargs)


class TestBuildReadme:
    def test_includes_title_and_summary(self):
        out = make_readme()
        assert "# Marimo Artifact" in out
        assert "A notebook that charts survival by class." in out

    def test_substitutes_filename_into_run_command(self):
        out = make_readme()
        assert "marimo edit artifact.py" in out
        assert "{filename}" not in out

    def test_lists_source_and_bundled_files(self):
        out = make_readme()
        assert "`artifact.py`" in out
        assert "`titanic.csv`" in out

    def test_includes_install_and_data_sections(self):
        out = make_readme()
        assert "## Installing dependencies" in out
        assert "pip install marimo pandas altair" in out
        assert "## Data" in out

    def test_includes_ai_disclaimer(self):
        assert "generated by AI" in make_readme()

    def test_omits_run_section_when_no_run_instructions(self):
        at = ArtifactType(
            id="other",
            label="Mystery",
            file_extension=".txt",
            description="",
            editor_language="plain",
        )
        out = make_readme(artifact_type=at, source_filename="artifact.txt")
        assert "## Running this artifact" not in out

    def test_omits_files_bundle_lines_when_none(self):
        out = make_readme(bundled_files=[])
        assert "`titanic.csv`" not in out
        assert "`artifact.py`" in out  # source is always listed

    def test_does_not_duplicate_source_in_file_list(self):
        out = make_readme(bundled_files=["artifact.py", "titanic.csv"])
        assert out.count("`artifact.py`") == 1
        assert "`titanic.csv`" in out

    def test_omits_summary_when_empty(self):
        out = make_readme(summary="")
        assert "# Marimo Artifact\n\n## Files" in out

    def test_omits_install_section_when_empty(self):
        out = make_readme(install_instructions="")
        assert "## Installing dependencies" not in out
