from querychat._handoff_data import external_dataframe_instructions
from querychat._handoff_readme import build_readme
from querychat._handoff_types import HandoffType, resolve_handoff_type


def make_readme(**overrides):
    kwargs = {
        "handoff_type": resolve_handoff_type("marimo-notebook", "python"),
        "source_filename": "handoff.py",
        "summary": "A notebook that charts survival by class.",
        "install_instructions": "```bash\npip install marimo pandas altair\n```",
        "run_instructions": ("Run it with:\n```bash\nmarimo edit handoff.py\n```"),
        "data_instructions": "A CSV named titanic.csv is bundled alongside.",
        "bundled_files": ["titanic.csv"],
    }
    kwargs.update(overrides)
    return build_readme(**kwargs)


class TestBuildReadme:
    def test_includes_title_and_summary(self):
        out = make_readme()
        assert "# Marimo Handoff" in out
        assert "A notebook that charts survival by class." in out

    def test_uses_generated_run_command(self):
        out = make_readme()
        assert "marimo edit handoff.py" in out

    def test_uses_current_run_instructions(self):
        out = make_readme(
            run_instructions="Run it with:\n```bash\nRscript handoff.R\n```"
        )
        assert "## Running this handoff" in out
        assert "Rscript handoff.R" in out

    def test_lists_source_and_bundled_files(self):
        out = make_readme()
        assert "`handoff.py`" in out
        assert "`titanic.csv`" in out

    def test_includes_install_and_data_sections(self):
        out = make_readme()
        assert "## Installing dependencies" in out
        assert "pip install marimo pandas altair" in out
        assert "## Data" in out

    def test_includes_ai_disclaimer(self):
        assert "generated by AI" in make_readme()

    def test_omits_run_section_when_no_run_instructions(self):
        at = HandoffType(
            id="other",
            label="Mystery",
            language="python",
            file_extension=".txt",
            editor_language="plain",
        )
        out = make_readme(
            handoff_type=at,
            source_filename="handoff.txt",
            run_instructions="",
        )
        assert "## Running this handoff" not in out

    def test_omits_files_bundle_lines_when_none(self):
        out = make_readme(bundled_files=[])
        assert "`titanic.csv`" not in out
        assert "`handoff.py`" in out  # source is always listed

    def test_externalized_dataframe_includes_warning_without_bundled_file_claim(self):
        out = make_readme(
            data_instructions=external_dataframe_instructions(
                "tips",
                "DuckDB",
                "python",
            ),
            bundled_files=[],
        )

        assert "This setup may need adjustment before the handoff can run." in out
        assert "`tips.csv`" not in out
        assert "bundled data file" not in out
        assert "fixed CSV snapshot" not in out

    def test_does_not_duplicate_source_in_file_list(self):
        out = make_readme(bundled_files=["handoff.py", "titanic.csv"])
        assert out.count("`handoff.py`") == 1
        assert "`titanic.csv`" in out

    def test_omits_summary_when_empty(self):
        out = make_readme(summary="")
        assert "# Marimo Handoff\n\n## Files" in out

    def test_omits_install_section_when_empty(self):
        out = make_readme(install_instructions="")
        assert "## Installing dependencies" not in out
